# ----------------------------------------------------------
# Spring Boot extra Config
# ----------------------------------------------------------
spring:
  messages:
    basename: i18n/messages
        