# ----------------------------------------------------------
# Spring Boot extra Config
# ----------------------------------------------------------
spring:
  messages:
    basename: i18n/messages

astra:
  api:
    application-token: ${ASTRA_DB_APPLICATION_TOKEN}
    database-id: 4fba8a47-04ed-45a5-8c29-46f28ccfec63
    database-region: us-east1
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: test